[package]
name = "bs"
version = "0.1.0"
authors = ["Peterson Trethewey <ptrethewey@roblox.com>"]
edition = "2018"

[dependencies]
clap = "2.26.0"
rust-crypto = "0.2.36"
base64 = "0.10.1"
sqlite = "0.25.0"
regex = "1.2.1"
multimap = "0.5.0"
