[package]
name = "ruler"
version = "0.1.0"
authors = ["Peterson Trethewey <peterson.trethewey@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.26.0"
rust-crypto = "0.2.36"
base64 = "0.10.1"
multimap = "0.5.0"
bincode = "1.1.4"
serde = { version = "1.0", features = ["derive"] }
filesystem = "0.4.4"
reqwest = "0.9.22"
