[package]
name = "ruler"
version = "0.1.0"
authors = ["Peterson Trethewey <peterson@2-complex.com>"]
description = "A straight-forward, general-purpose build tool"
homepage = "https://rulerbuild.com"
repository = "https://github.com/2-complex/ruler"
edition = "2020"
readme = "README.md"

[dependencies]
clap = "2.26.0"
rust-crypto = "0.2.36"
base64 = "0.10.1"
multimap = "0.5.0"
bincode = "1.1.4"
serde = { version = "1.0", features = ["derive"] }
filesystem = { git = "https://github.com/TheSven73/filesystem-rs.git", branch = "file-objects-v2" }
reqwest = "0.9.22"

hyper = "0.10"
hyper-native-tls = "0.2.4"
multipart = "0.13.1"
lipsum = "0.6.0"

termcolor = "1"
