#!/usr/local/bin/python

import argparse

parser = argparse.ArgumentParser(description='Concatinate files to make a poem.')
parser.add_argument('files', metavar='F', type=str, nargs='+', help='files to concatinate')
parser.add_argument('--target', dest='target', help='target file to hold the output', required=True)

args = parser.parse_args()

poem_list = []
for file in args.files:
    with open(file, "r") as f:
        poem_list.append(f.read())

with open(args.target, "w") as f:
    f.write("".join(poem_list))
